### ISSUE TITLE
Remove deprecated <center> tags

### ISSUE THREAD

**Issue by pdnelson** [pdnelson/My-Personal-Website#3]
These tags should be replaced with `text-align: center`.

Add a class in the `MainStyle.css` file, and rename the current `center` class to something else.

**Comment by Saisrinivenkat** [comment]
Shall I help u to enhance this?

**Comment by pdnelson** [comment]
@Saisrinivenkat, I just need to find the time between classes to do it. These issues primarily exist so I don't forget to do stuff, but thank you for the offer!
